name: CI

on:
  push:
    branches:
      - '*'
      - 'feature/*'
      - 'hotfix/*'
      - 'bugfix/*'
      - 'release/*'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Récupération du code
        uses: actions/checkout@v6.0.3

      - name: Install npm
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.16.0

      - name: Install npm dependencies
        run: npm ci --ignore-scripts && npm rebuild sqlite3

      - name: Create env file
        run: |
          cat .env.example > .env.test
          sed -i -e "s/__NODE_ENV__/test/g" ./.env.test
          sed -i -e "s/__APP_NAME__/nestjs/g" ./.env.test
          sed -i -e "s/__APP_PORT__/3000/g" ./.env.test
          sed -i -e "s/__DB_TYPE__/sqlite/g" ./.env.test
          sed -i -e "s#__DB_NAME__#src/database/test#g" ./.env.test
          sed -i -e "s/__DB_DEBUG__/false/g" ./.env.test
          sed -i -e "s/__INTERVAL_MS__/1000/g" ./.env.test

      - name: Build assets
        run: npm run build

      - name: Run linter
        run: npm run lint

      - name: Run database migration
        run: npm run migration:run

      - name: Run test
        run: npm run test:cov

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # 8.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
